### PR TITLE
Add Hyprland Automate Execution

### PR DESCRIPTION
**Pull request by NextWork123**
Hello, I'd like to introduce an automated execution of Hyprland after login. Let me explain how I achieve this. First, I check if the Hyprland command is present. Then, I check if the DISPLAY environment variable is empty and XDG_VTNR is equal to 1. If both conditions are met, I execute Hyprland without any issues. If the user doesn't have Hyprland installed on their system, nothing will happen.

Best Regards,
NextWorks

### CODE REVIEW

**Comment by ptr1337** [comment]
Mhm. General a good idea, but I don't know if DE/WM related stuff should land into the default fish config, which is used by every Installation.
I think we should move this to cachyos-hyprland-settings probably, somehow ?

**Comment by ventureoo** [comment]
Well, why not just use the display manager?

**Comment by NextWork123** [comment]
Isn't suggested by dev to use display manager.

**Comment by ptr1337** [comment]
We already use as default light dm right now for the hyprland installation. We need to set at calamares one displaymanager, otherwise it will symlink to a random one.

**Comment by NextWork123** [comment]
For my personal judge i don't like to put more depends/packages for only login thing (if we can bypass display manager and be more safe with a little check on the fish shell or other shells isn't bad we can do too for sway and so other).

**Comment by NextWork123** [comment]
At least some display manager can have trouble and we need to solve. on wiki of hyprland is mentioned that: 

Login managers are not officially supported, but here’s a short compatibility list

SDDM → Works flawlessly. Install the [latest git version](https://github.com/sddm/sddm) (or [sddm-git](https://aur.archlinux.org/packages/sddm-git) from the AUR if you use Arch) to prevent SDDM bug [1476](https://github.com/sddm/sddm/issues/1476) (90s shutdowns).
GDM → Works with the caveat of crashing Hyprland on the first launch
 ly → Works poorl

**Comment by ventureoo** [comment]
> At least some display manager can have trouble and we need to solve. on wiki of hyprland is mentioned that:
> 
> Login managers are not officially supported, but here’s a short compatibility list
> 
> SDDM → Works flawlessly. Install the [latest git version](https://github.com/sddm/sddm) (or [sddm-git](https://aur.archlinux.org/packages/sddm-git) from the AUR if you use Arch) to prevent SDDM bug [1476](https://github.com/sddm/sddm/issues/1476) (90s shutdowns). GDM → Works with the caveat of crashing Hyprland on the first launch ly → Works poorl

WTF, how does display manager selection even affect hyprland?

**Comment by NextWork123** [comment]
> > At least some display manager can have trouble and we need to solve. on wiki of hyprland is mentioned that:
> > Login managers are not officially supported, but here’s a short compatibility list
> > SDDM → Works flawlessly. Install the [latest git version](https://github.com/sddm/sddm) (or [sddm-git](https://aur.archlinux.org/packages/sddm-git) from the AUR if you use Arch) to prevent SDDM bug [1476](https://github.com/sddm/sddm/issues/1476) (90s shutdowns). GDM → Works with the caveat of crashing Hyprland on the first launch ly → Works poorl
> 
> WTF, how does display manager selection even affect hyprland?

Don't tell me i mentioned the wiki xd,anyway i leave the choice to ptr and vlad. the pull is here if someone want to merge

**Comment by vnepogodin** [comment]
We should never force any WM/DE to the user. your approach here will start Hyprland everytime if you login from TTY

**Comment by NextWork123** [comment]
> We should never force any WM/DE to the user. your approach here will start Hyprland everytime if you login from TTY

Nop, you are wrong i check if is installed Hyprland first and after i do other checks.

**Comment by NextWork123** [comment]
anyway gonna close that pull i will not contribute about that.

**Pull request closed without merging**
